apiVersion: v1
kind: Namespace
metadata:
  name: lab5

---

apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota-lab5
  namespace: lab5
spec:
  hard:
    pods: "10"
    cpu: "2"
    memory: 1.5Gi

---

apiVersion: v1
kind: Pod
metadata:
  name: worker
  namespace: lab5
spec:
  containers:
  - name: nginx-container
    image: nginx
    resources:
      limits:
        memory: 200Mi
        cpu: 200m
      requests:
        memory: 100Mi
        cpu: 100m

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-apache
  namespace: lab5
spec:
  selector:
    matchLabels:
      run: php-apache
  template:
    metadata:
      labels:
        run: php-apache
    spec:
      containers:
      - name: php-apache
        image: registry.k8s.io/hpa-example
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: 250Mi 
            cpu: 250m
          requests:
            memory: 150Mi 
            cpu: 150m

---

apiVersion: v1
kind: Service
metadata:
  name: php-apache
  namespace: lab5 
  labels:
    run: php-apache
spec:
  ports:
  - port: 80
  selector:
    run: php-apache

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: php-apache
  namespace: lab5 
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: php-apache
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50