apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: "2023-12-12T11:34:04Z"
  generation: 1
  name: web-ingress
  namespace: default
  resourceVersion: "2757"
  uid: b1de6a39-e4ee-45ca-aa7f-905635aef523
spec:
  ingressClassName: nginx
  rules:
  - host: lab9.info
    http:
      paths:
      - backend:
          service:
            name: web
            port:
              number: 8080
        path: /
        pathType: Exact
status:
  loadBalancer:
    ingress:
    - ip: 192.168.49.2
