apiVersion: v1
kind: Namespace
metadata:
  name: lab4

---

apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota-zad5
  namespace: zad5
spec:
  hard:
    pods: "10"
    cpu: "2"
    memory: 1.5Gi
