apiVersion: v1
kind: Namespace
metadata:
  name: lab5

---

apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota-lab5
  namespace: lab5
spec:
  hard:
    pods: "10"
    cpu: "2"
    memory: 1.5Gi
