apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: multicontainer
  name: multicontainer
spec:
  containers:
  - args:
    - sleep
    - "3600"
    image: busybox
    name: busybox
    resources: {}
  - name: nginx
    image: nginx
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}